name: 'Milestones Changelog'
description: 'Creates changelog based on all milestones.'
inputs:
  branch:
    description: 'Branch used to get list of milestones, possible values "all" or "name of branch".'
    default: all
    required: true
  state:
    description: 'State of milestones to collect, possible values "all", "closed" or "open".'
    default: closed
    required: true
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  config:
    description: 'Path to file or config as value with generate settings. (Possible representation types: "Json" or "Yaml".)'
    default: .github/milestones-changelog.yml
    required: true
  output:
    description: 'Path to output result as file.'
    required: false
outputs:
  result:
    description: 'Action result.'
runs:
  using: 'node12'
  main: 'dist/index.js'
